name: Actions reliability checks line tool workflow

on: [push]

jobs:
  action:
    runs-on: "macos-latest"

    steps:
     - uses: actions/checkout@v1
     - name: Install scorecard
       run: brew install scorecard
     - name: Run checks
       uses: ./.github/actions/checks
       with:
        token: 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
        checkName: "Branch-Protection"
