name: Actions reliability checks line tool workflow

on: [push]

jobs:
  action:
    runs-on: "ubuntu-latest"


    steps:
     - uses: actions/checkout@v1
     - name: Run checks
       uses: ./.github/actions/checks
