# To create a customizable workflow that will - 
# - have clear permissions
# - take inputs and use them to run only specified checks
# - handle errors
# - create a SARIF and upload it as an artifact
#  - upload the SARIF file to code scanning service
# Dependabot example workflow file: https://github.com/github/dependabot-api/blob/main/app/actions/run_updater/actions/workflow.rb

name: Security Checks for Actions on Marketplace
on: dynamic
  # workflow_dispatch:
  # push: 

jobs: 
  run-security-checks:
    name: Actions Security Checks
    runs-on: runner_type # self_hosted or cloud 
    permissions:
      contents: read
      id-token: read
      # Needed to upload the results to code-scanning dashboard.
      security-events: write
    steps:
      - uses: actions/checkout@v1
      
      # Set up Go Environment
      - name: Setup Go environment
        uses: actions/setup-go@v3.5.0
    
      # Install Standalone Command Line Tool for OSSF
      - name: Install OSSF Command Line Tool
        run: |
             curl -OL https://github.com/ossf/scorecard/releases/download/v4.10.2/scorecard_4.10.2_linux_amd64.tar.gz
             tar -xf scorecard_4.10.2_linux_amd64.tar.gz
            
      # Run Checks Store Output
      - name: Run Security Checks
        run: |
              export GITHUB_AUTH_TOKEN=${{secrets.OSSF_PAT}}
              ENABLE_SARIF=true ./scorecard-linux-amd64 --repo=github.com/shruti-shukla/fuzzy-adventure --checks=check_names --policy=policy.yaml --format=sarif
              
      # Create/Modify Sarif using the Output
      # Store SARIF ID as artifact
      # Upload SARIF file to Code scanning service
    

