name: OSSF command line tool workflow Ubuntu

on: [push]

jobs:
  action:
    runs-on: "ubuntu-latest"

    steps:
 
    - name: Setup Go environment
      uses: actions/setup-go@v3.5.0
    - name: Get Scorecard release 
      run: curl -OL https://github.com/ossf/scorecard/releases/download/v4.10.2/scorecard_4.10.2_linux_amd64.tar.gz
    - name: Extract tar
      run: | 
           tar -xf scorecard_4.10.2_linux_amd64.tar.gz
           ls
    - name: Go to scorecard directory
      run: | 
      echo "version: 1
            policies:
              Token-Permissions:
                  score: 10
                  mode: enforced
              Branch-Protection:
                  score: 10
                  mode: enforced
              Code-Review:
                  score: 10
                  mode: enforced
              Dangerous-Workflow:
                  score: 10
                  mode: enforced
              License:
                  score: 10
                  mode: enforced
              Pinned-Dependencies:
                  score: 10
                  mode: enforced
              Security-Policy:
                  score: 10
                  mode: enforced
              SAST:
                  score: 10
                  mode: enforced
              Contributors:
                  score: 10
                  mode: disabled
              Packaging:
                  score: 10
                  mode: enforced
              Binary-Artifacts:
                  score: 10
                  mode: enforced
              Signed-Releases:
                  score: 10
                  mode: disabled
              Dependency-Update-Tool:
                  score: 10
                  mode: enforced
              Fuzzing:
                  score: 10
                  mode: enforced
              CII-Best-Practices:
                  # passing score
                  score: 5
                  mode: enforced
              Vulnerabilities:
                  score: 10
                  mode: enforced
              CI-Tests:
                  score: 10
                  mode: enforced
              Maintained:
                  score: 1
            mode: enforced" >> policy.yml
    - name: set github auth token and run scorecard
      run: |
              export GITHUB_AUTH_TOKEN=${{secrets.OSSF_PAT}}
              ENABLE_SARIF=true ./scorecard-linux-amd64 --repo=github.com/shruti-shukla/fuzzy-adventure --checks=Dangerous-Workflow,Binary-Artifacts,Branch-Protection,Code-Review,Dependency-Update-Tool,Vulnerabilities,Pinned-Dependencies,SAST,Security-Policy --format=sarif

