name: OSSF command line tool workflow Ubuntu

on: [push]

jobs:
  action:
    runs-on: "ubuntu-latest"

    steps:
     
     - name: download command line tool
       run: brew install scorecard
     - name: set github auth token and run scorecard
       run: |
              export GITHUB_AUTH_TOKEN=${{secrets.OSSF_PAT}}
              scorecard --repo=github.com/shruti-shukla/fuzzy-adventure --checks=Dangerous-Workflow,Binary-Artifacts,Branch-Protection,Code-Review,Dependency-Update-Tool,Vulnerabilities,Pinned-Dependencies,SAST,Security-Policy --show-details

