name: OSSF command line tool workflow Ubuntu

on: [push]

jobs:
  action:
    permissions: 
      security-events: write
      contents: write 

    runs-on: "ubuntu-latest"
    env: 
      GITHUB_AUTH_TOKEN: ${{secrets.INSTALLATION_ACCESS_TOKEN}}
    steps:
 
    - name: Setup Go environment
#     uses: actions/setup-go@v3.5.0
      run: go version
    - name: Get Scorecard release 
      run: curl -OL https://github.com/ossf/scorecard/releases/download/v4.10.2/scorecard_4.10.2_linux_amd64.tar.gz
    - name: Extract tar
      run: | 
           tar -xf scorecard_4.10.2_linux_amd64.tar.gz
           ls
    - name: Go to scorecard directory
      run: echo "${{ vars.POLICY }}" >> policy.yaml
    #ENABLE_SARIF=true ./scorecard-linux-amd64 --repo=github.com/shruti-shukla/fuzzy-adventure --checks=Dangerous-Workflow,Binary-Artifacts,Branch-Protection,Code-Review,Dependency-Update-Tool,Vulnerabilities,Pinned-Dependencies,SAST,Security-Policy --policy=policy.yaml --format=sarif > results.sarif
    - name: set github auth token and run scorecard
       #export GITHUB_AUTH_TOKEN=${{secrets.INSTALLATION_ACCESS_TOKEN}}
      run: |  
              export GITHUB_AUTH_TOKEN=${{secrets.INSTALLATION_ACCESS_TOKEN}}
              ./scorecard-linux-amd64 --repo=github.com/shruti-shukla/fuzzy-adventure --checks=Dangerous-Workflow,Binary-Artifacts,Branch-Protection,Code-Review,Dependency-Update-Tool,Vulnerabilities,Pinned-Dependencies,SAST,Security-Policy --show-details
    - name: Check contents of file
      run: | 
          ls
          cat results.sarif

