name: OSSF command line tool workflow

on: [push]

jobs:
  action:
    runs-on: "macos-12"

    steps:
     
     - name: download command line tool
       run: brew install scorecard
     - name: set github auth token and run scorecard
       run: |
              export GITHUB_AUTH_TOKEN=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
              scorecard --repo=github.com/shruti-shukla/fuzzy-adventure --checks Branch-Protection --show-details

