name: OSSF command line tool workflow Ubuntu

on: [push]

jobs:
  action:
    runs-on: "ubuntu-latest"

    steps:
 
    - name: Setup Go environment
      uses: actions/setup-go@v3.5.0
    - name: Get Scorecard release 
      run: curl -OL https://github.com/ossf/scorecard/releases/download/v4.10.2/scorecard_4.10.2_linux_amd64.tar.gz
    - name: Extract tar
      run: | 
           tar -xf scorecard_4.10.2_linux_amd64.tar.gz
           ls
    - name: Go to scorecard directory
      run: echo "${{ vars.POLICY }}" >> policy.yaml
    - name: set github auth token and run scorecard
      run: |
              export GITHUB_AUTH_TOKEN=${{secrets.OSSF_PAT}}
              ENABLE_SARIF=true ./scorecard-linux-amd64 --repo=github.com/shruti-shukla/fuzzy-adventure --checks=Dangerous-Workflow,Binary-Artifacts,Branch-Protection,Code-Review,Dependency-Update-Tool,Vulnerabilities,Pinned-Dependencies,SAST,Security-Policy --format=sarif

